# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    container: node:14.7.0

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - name: checkout repository code
      uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: configure variables
      run: |
        sed -i -e "s|forum_api_dev|postgres|g" .env && \
        sed -i -e "s|devel|postgres|g" .env && \
        sed -i -e "s|secret|postgres|g" .env
    - name: setup database
      run: npm run migrate:latest
      env:
        PGHOST: postgres
    - name: run postman
      run: npm run test:postman
    - name: do functional test
      run: npm test -- --detectOpenHandles --forceExit
      env:
        PGHOST: postgres
        NODE_ENV: test
